### PR TITLE
Improve error/exception reporting + improve stabilizer + momentum task

### PR DESCRIPTION
**Pull request by jbmouret**
This adds:
- a print of the stack when we receive an exception
- a new macro IWBC_CHECK that allows us to print the stack when the exception is triggered by another library (esp. yaml-cpp). now the line number (98 below) corresponds to the call to yaml-cpp, therefore we know what is wrong by checking this line.

This looks like this (you might have line numbers on Linux):
```
Error (exception): inria_wbc:: bad conversion   [/Users/jmouret/git/resibots/inria_wbc/src/controllers/pos_tracker.cpp:98]
------ stack ------
 0# inria_wbc::Exception::Exception<char const*>(char const*, int, char const*) in /Users/jmouret/git/resibots/inria_wbc/build/libinria_wbc.dylib
 1# inria_wbc::controllers::PosTracker::parse_tasks(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in /Users/jmouret/git/resibots/inria_wbc/build/libinria_wbc.dylib
 2# inria_wbc::controllers::PosTracker::PosTracker(inria_wbc::controllers::Controller::Params const&) in /Users/jmouret/git/resibots/inria_wbc/build/libinria_wbc.dylib
 3# inria_wbc::controllers::TalosPosTracker::TalosPosTracker(inria_wbc::controllers::Controller::Params const&) in /Users/jmouret/git/resibots/inria_wbc/build/libinria_wbc.dylib
 4# std::__1::__function::__func<inria_wbc::utils::Factory<inria_wbc::controllers::Controller, inria_wbc::controllers::Controller::Params>::AutoRegister<inria_wbc::controllers::TalosPosTracker>::AutoRegister(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(inria_wbc::controllers::Controller::Params const&), std::__1::allocator<inria_wbc::utils::Factory<inria_wbc::controllers::Controller, inria_wbc::controllers::Controller::Params>::AutoRegister<inria_wbc::controllers::TalosPosTracker>::AutoRegister(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::'lambda'(inria_wbc::controllers::Controller::Params const&)>, std::__1::shared_ptr<inria_wbc::controllers::Controller> (inria_wbc::controllers::Controller::Params const&)>::operator()(inria_wbc::controllers::Controller::Params const&) in /Users/jmouret/git/resibots/inria_wbc/build/libinria_wbc.dylib
 5# inria_wbc::utils::Factory<inria_wbc::controllers::Controller, inria_wbc::controllers::Controller::Params>::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, inria_wbc::controllers::Controller::Params const&) const in /Users/jmouret/git/resibots/inria_wbc/build/./test_controller_graphics
 6# main in /Users/jmouret/git/resibots/inria_wbc/build/./test_controller_graphics
```

### CODE REVIEW

**Comment by jbmouret** [comment]
According to the CI, the boost of Ubuntu 16.04 is too old!

`/tmp/inria_wbc/include/inria_wbc/exceptions.hpp:7:55: fatal error: boost/stacktrace.hpp: No such file or directory`

It seems to be possible in unbuntu 18.04 (good things we should get the update soon!).

**Comment by jbmouret** [comment]
Should we merge this? this is useful for debugging.

**Comment by dalinel** [comment]
Are the tests working on your computer ? 
If yes we can merge

**Comment by jbmouret** [comment]
I have an error for the clapping (all variants):
```
test_behaviors_talos.cpp:324: error: in "behaviors": lh tolerance --> 0.017225 > 0.001000
test_behaviors_talos.cpp:325: error: in "behaviors": lh tolerance --> 0.017423 > 0.001000
est_behaviors_talos.cpp:324: error: in "behaviors": rh tolerance --> 0.016975 > 0.001000
test_behaviors_talos.cpp:325: error: in "behaviors": rh tolerance --> 0.017172 > 0.001000
```

Not sure what to read about this... this could be that mac + clang + many other differences result in a slightly different self-collision behavior. 

However, I think the test will always be only 100% valid in the docker and this is where we should check.

**Comment by dalinel** [comment]
Ok I have merged the work from #27  and the com stabilizer modification to include velocity reference here
Hence I have changed the reference
It works on my docker so it should work on the CI computers

**Comment by dalinel** [comment]
Should we merge ?

**Comment by jbmouret** [comment]
Can we close the branch and the PR?

**Comment by ivanbergonzani** [comment]
All fine to me

**Pull request merged**
