### PR TITLE
Load save trajs

### PR DESCRIPTION
**Pull request by jbmouret**
This adds utilities to save & load CSV trajectories. The objective is to be able to use a selection fo trajectories from teleoperation and play them without the teleoperation module.

This should also be useful if we generate trajectories with another tool (e.g., a trajectory optimization module) and want to quickly see what happens.

I created a new `trajs::` namespace, so I think we should move the trajectory generators there (`utils/trajectory_handler.hpp`).

### CODE REVIEW

**Comment by ivanbergonzani** [comment]
header "inria_wbc/behaviors/generic/cartesian_traj.hpp" is missing

Maybe we can think about adding joint trajectory saving/loading, it might make sense for manipulators

**Comment by ivanbergonzani** [comment]
ok for me
strangely I had a existing "time" (without underscore) variable in the cartesian_traj behavior update method  but I cannot find  where it is declared

**Comment by jbmouret** [comment]
Maybe the function time() from sys.h?

**Comment by ivanbergonzani** [comment]
yes that's it. I think we can merge

**Comment by jbmouret** [comment]
@dalinel ?

**Comment by dalinel** [comment]
Ok for me !

**Pull request merged**
