### PR TITLE
Improve stabilizer

### PR DESCRIPTION
**Pull request by dalinel**
Adds/Improve methods for stabilization :

- **com admittance** :
Takes global cop sensor feedback and modify the com tsid reference accordingly
- **ankle admittance**
Takes the cop sensor feedback of one foot and modifies the ankle roll and pitch to keep the cop in the middle of the foot
- **foot force difference admittance**
Compares the left and right foot force difference recorded by the sensors to the tsid foot force difference
It modifies the torso roll to track the tsid foot force difference

It improves the stability but adds more pid tuning
First tune the position gains, then velocity and then acceleration
Check the results with the ```-p -n -l``` options of ```test_controllers``` and with ```make check```

### CODE REVIEW

**Comment by dalinel** [comment]
In order to keep two separated  behavior/controller yaml files I had to create a behavior_type section (fixed_base, single_support, double_support)
It allows to select the correct stabilization gains inside the controller

**Comment by jbmouret** [comment]
Since the controller is now disconnected from the behavior yaml, why do we need the type? we could just choose the right controller for the right behavior when we load the files, right?

Also, I would prefer strings to numbers.

**Comment by dalinel** [comment]
Right now a behavior can be used with several controllers
If we specify that a behavior must be used with a  specific controller we loose some flexibility

The type is used to load the correct stabilization weights inside the controller (single_support vs double_support)

**Comment by jbmouret** [comment]
I see. This could make sense when a behavior changes from single to double support and therefore needs different stabilizers.

Anyway, I am fine with it and we will see later if we are happy with this.

**Comment by ivanbergonzani** [comment]
Really Good work!!! I played with it and works well. I have only some considerations about code

I also think that string are better than numbers for the behavior type. with strings it is clear at first glance and it is less error prone.

Once merged with no float base dev it'd be possible also to remove the fixed base gains (which if I am not wrong should do nothing) and just check in the controller if it is floating base or not. 

Maybe the behavior_type should not be in a YAML file since it depends strictly on the behavior and it is not something you want to configure (otherwise we give the possibility to set fixed base gains for walk_on_spot for example). So maybe we can use an abstract method in the behavior base class to set the initial behavior type. Each behavior will implement by returning its type. 
Something like:

```
int Behavior::behavior_type() const = 0; 

Behavior::Behavior(  ... ) {
   ...
   int bt = this->behavior_type();
   controller_->set_behavior_type(bt);
   ...
}

int ArmBehavior::behavior_type() const
{ 
    return _arm_beh_type; // 2 
}
```

In the controller class I will put the stabilization constexpr types inside an enum class or struct to separate them from the other class attributes. 
Also, since the base controller does not have stabilization, maybe we should move these constexpr attributes directly in TalosPosController which actually use them?


Little note
in the stabilization methods it  hould be possible to change 
``` p.block(2, 0, 1, 2)``` or ``` p.block<1,2>(2,0) ``` (also here ncols - nrows are inverted, it works the same just because vectors have 1 col)
with
``` p.segment<2>(2) ``` 
which is the actual method for vectors

https://github.com/resibots/inria_wbc/blob/da9d373999d33b5a12601e57f94c32c75376c4bf/src/stabilizers/stabilizer.cpp#L76

**Comment by dalinel** [comment]
Thanks for checking the PR :+1: !

> we will see later if we are happy with this.

yes let's see if this works, if not we can do a later PR

> I also think that string are better than numbers for the behavior type. with strings it is clear at first glance and it is less error prone.

ok let's switch to string types

> Once merged with no float base dev it'd be possible also to remove the fixed base gains (which if I am not wrong should do nothing) and just check in the controller if it is floating base or not.

yes we can remove that when we merge the PR #36 

>Maybe the behavior_type should not be in a YAML file since it depends strictly on the behavior and it is not something you want to configure 

Yes good idea! Let's add this with the abstract method in the behavior class

>  In the controller class I will put the stabilization constexpr types inside an enum class or struct to separate them from the other class attributes.

Ok yes it will be cleaner

>  Also, since the base controller does not have stabilization, maybe we should move these constexpr attributes directly in TalosPosController which actually use them?

True we can do that for now since we don't have several controller using stabilization
We can change that some day if we need several controllers based on this stabilization

> with
p.segment<2>(2)
which is the actual method for vectors

yes true

**Pull request merged**
