### PR TITLE
Measured force as a new kind of task

### PR DESCRIPTION
**Pull request by Groulaxx**
This PR is related to the issue ["ForceTask with moving object"](https://github.com/stack-of-tasks/tsid/issues/176)

This adds a measured_force for moving contacts with external objects

Also a quick fix for Boost and comptatibility with the last stack-of-tasks/tsid devel branch

### CODE REVIEW

**Comment by jbmouret** [comment]
@olivierrochel-inria Can you have a look?

**Comment by Groulaxx** [comment]
The TSID PR passed last week so I think it's fine to merge here, but I just saw that there is a lot of modification just because of the auto-format of my IDE, I don't know if it's a problem for you to have both format and content modification at the same time ?

**Comment by jbmouret** [comment]
It would be better to avoid format changes...

**Comment by Groulaxx** [comment]
Okay I reversed all the format changes, so it should be fine now

**Comment by olivierrochel-inria** [comment]
Hello, I'll have a look. As for the boost/cmake fix: it would be better if it was fixed on pinocchio's side, I did not raise the issue there yet, I'll do it asap.

**Comment by olivierrochel-inria** [comment]
About the boost/cmake fix again: the fix I've suggested to Justin did not work on pinocchio's side (seems to break things in python) so we'll have to make it work on our side instead. As it is not related to this PR I'll submit another one dedicated to that issue for better traceability (#120)

**Comment by olivierrochel-inria** [comment]
With the last changes by Nicolas I think this can be merged. @jbmouret do you agree ?

**Comment by jbmouret** [comment]
Yes, OK.

**Pull request merged**
